CREATE DATABASE BANCO_PROJ1;

USE BANCO_PROJ1;

# CRIANDO TABELAS

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    SEXO ENUM('F', 'M'),
    NASCIMENTO VARCHAR(10),
    EMAIL VARCHAR(50)
);

CREATE TABLE TELEFONE(
	IDCONTATO INT PRIMARY KEY AUTO_INCREMENT,
    DDD INT(2) NOT NULL,
    NUMERO VARCHAR(9) NOT NULL,
    ID_CLIENTE INT
);

#CREATE TABLE ESTADO(
#	IDESTADO INT PRIMARY KEY AUTO_INCREMENT,
#    NOMEESTADO CHAR(2)
#);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(50) NOT NULL,
    NUM INT(5),
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50)NOT NULL,
    ESTADO CHAR(2) NOT NULL,
#    ID_ESTADO INT,
    ID_CLIENTE INT
);

/*
CREATE TABLE VENDA(
	IDVENDA INT PRIMARY KEY AUTO_INCREMENT,
    VALOR FLOAT(7,2) NOT NULL,
    DATAVENDA VARCHAR(10),
    PRODUTO VARCHAR(30) NOT NULL,
    ID_CLIENTE INT
);
*/

# CONSTRAINTS

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE) ON DELETE CASCADE;

#ALTER TABLE ENDERECO
#ADD CONSTRAINT FK_ENDERECO_ESTADO
#FOREIGN KEY(ID_ESTADO)
#REFERENCES ESTADO(IDESTADO);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE) ON DELETE CASCADE;
/*
ALTER TABLE VENDA
ADD CONSTRAINT FK_VENDA_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE) ON DELETE CASCADE;
*/
/*
INSERT INTO ESTADO VALUES(NULL, 'AC');
INSERT INTO ESTADO VALUES(NULL, 'AL');
INSERT INTO ESTADO VALUES(NULL, 'AP');
INSERT INTO ESTADO VALUES(NULL, 'AM');
INSERT INTO ESTADO VALUES(NULL, 'BA');
INSERT INTO ESTADO VALUES(NULL, 'CE');
INSERT INTO ESTADO VALUES(NULL, 'DF');
INSERT INTO ESTADO VALUES(NULL, 'ES');
INSERT INTO ESTADO VALUES(NULL, 'GO');
INSERT INTO ESTADO VALUES(NULL, 'MA');
INSERT INTO ESTADO VALUES(NULL, 'MT');
INSERT INTO ESTADO VALUES(NULL, 'MS');
INSERT INTO ESTADO VALUES(NULL, 'MG');
INSERT INTO ESTADO VALUES(NULL, 'PA');
INSERT INTO ESTADO VALUES(NULL, 'PB');
INSERT INTO ESTADO VALUES(NULL, 'PR');
INSERT INTO ESTADO VALUES(NULL, 'PE');
INSERT INTO ESTADO VALUES(NULL, 'PI');
INSERT INTO ESTADO VALUES(NULL, 'RJ');
INSERT INTO ESTADO VALUES(NULL, 'RN');
INSERT INTO ESTADO VALUES(NULL, 'RS');
INSERT INTO ESTADO VALUES(NULL, 'RO');
INSERT INTO ESTADO VALUES(NULL, 'RR');
INSERT INTO ESTADO VALUES(NULL, 'SC');
INSERT INTO ESTADO VALUES(NULL, 'SP');
INSERT INTO ESTADO VALUES(NULL, 'SE');
INSERT INTO ESTADO VALUES(NULL, 'TO');
*/
SHOW TABLES;

/* INSERIR/CADASTRAR CLIENTES */

INSERT INTO CLIENTE VALUES(NULL, 'ANA MARIA', 'F', '15/10/2000', 'ANINHA.M@GMAIL.COM');
INSERT INTO CLIENTE VALUES(NULL, 'JOAO CARLOS', 'M', '03/05/1981', 'JOCA@IG.COM');
INSERT INTO CLIENTE VALUES(NULL, 'JOSE NETO', 'M', '30/07/1995', 'ZEZINHO@HOTMAIL.COM');
INSERT INTO CLIENTE VALUES(NULL, 'VIVIAN SOUZA', 'F', '10/12/1976', 'VINHA.S@OUTLOOK.COM');
INSERT INTO CLIENTE VALUES(NULL, 'MARIA CLARA', 'F', '15/01/1996', 'M.CLARINHA@IG.COM');

SELECT * FROM CLIENTE;

/* INSERIR TELEFONE DE CONTATO */

INSERT INTO TELEFONE VALUES(NULL, '71', '984572236', 1);
INSERT INTO TELEFONE VALUES(NULL, '71', '35213025', 1);
INSERT INTO TELEFONE VALUES(NULL, '21', '982654854', 3);
INSERT INTO TELEFONE VALUES(NULL, '11', '32546587', 2);
INSERT INTO TELEFONE VALUES(NULL, '75', '982547826', 4);
INSERT INTO TELEFONE VALUES(NULL, '71', '956854723', 5);

SELECT * FROM TELEFONE;

# SELECT * FROM ESTADO;

SELECT * FROM TELEFONE;

/* INSERIR ENDERECO */

INSERT INTO ENDERECO VALUES(NULL, 'DOM JOAO VI', 10, 'PITUBA', 'SALVADOR', 'BA', 1);
INSERT INTO ENDERECO VALUES(NULL, 'SANTO ANTONIO', 1001, 'BARRA DA TIJUCA', 'RIO DE JANEIRO', 'RJ', 3);
INSERT INTO ENDERECO VALUES(NULL, 'DOM JOAO VI', 25, 'CONSOLAÇÃO', 'SÃO PAULO', 'SP', 2);
INSERT INTO ENDERECO VALUES(NULL, 'R QUINZE', 350, 'CENTRO', 'SANTO ANTONIO DE JESUS', 'BA', 4);
INSERT INTO ENDERECO VALUES(NULL, 'R DAS PEDRINHAS', 21, 'PERIPERI', 'SALVADOR', 'BA', 5);

SELECT * FROM ENDERECO;

/* INSERIR DADOS DE COMPRA */
/*
INSERT INTO VENDA VALUES(NULL, 99.99, '06/05/2023', 'CAMISA AZUL', 3);
INSERT INTO VENDA VALUES(NULL, 350.00, '06/05/2023', 'TENIS', 2);
INSERT INTO VENDA VALUES(NULL, 159.90, '06/05/2023', 'VESTIDO FLORAL', 4);
INSERT INTO VENDA VALUES(NULL, 75.00, '06/05/2023', 'BLUSA AMARELA', 1);
INSERT INTO VENDA VALUES(NULL, 150.00, '06/05/2023', 'CAMISA ESTAMPADA', 2);
INSERT INTO VENDA VALUES(NULL, 220.80, '06/05/2023', 'CALÇA BRANCA', 3);
INSERT INTO VENDA VALUES(NULL, 65.00, '12/03/2023', 'CINTO', 5);

SELECT * FROM VENDA;
*/
/* SELECIONAR ALGUNS DADOS DO CLIENTE (NOME, EMAIL, CIDADE, PRODUTO E VALOR DE COMPRA */

SELECT C.NOME, C.EMAIL, E.CIDADE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

/* ALTERAR DADOS DO CLIENTE */

SELECT * FROM CLIENTE
WHERE NOME LIKE '%MARIA%';

UPDATE CLIENTE
SET EMAIL = 'MARIA.CLARA@GMAIL.COM'
WHERE IDCLIENTE = 5;

/* TOTAL JÁ COMPRADO POR DETERMINADO CLIENTE 

SELECT C.IDCLIENTE, C.NOME, SUM(V.VALOR) AS 'TOTAL DO CLIENTE'
FROM CLIENTE C
INNER JOIN VENDA V
ON C.IDCLIENTE = V.ID_CLIENTE
GROUP BY IDCLIENTE;
*/
USE BANCO_PROJ1;

SELECT * FROM ENDERECO; 

UPDATE CLIENTE
SET EMAIL = 'MARIA.CLARA@GMAIL.COM'
WHERE IDCLIENTE = 5;




















